pipeline:
  processors:
    - mapping: file://./resources/processors/canonicalize_kubernetes.blobl
    - resource: welkin_validate_cloudevent
    - catch:
        - log:
            level: ERROR
            message: 'Dropping invalid canonical event due to: ${! error() }'
        - mapping: 'root = deleted()'

output:
  broker:
    pattern: fan_out
    outputs:
      - resource: welkin_runtime_openmeter
      - drop_on:
          back_pressure: 30s
          output:
            resource: welkin_archive_s3
